title: "Алгоритмы и структуры данных на C++"
author: "Yuliya"

execute:
  execute_notebooks: "off"

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  use_thebe: false            # ← временно отключаем

repository:
  url: https://github.com/yuliya-sabirova/cpp-ads-course
  branch: main
  path_to_book: ""

launch_buttons:
  binderhub_url: https://mybinder.org
