title: "Алгоритмы и структуры данных на C++"
author: "Eldar"

execute:
  execute_notebooks: "off"   # не исполняем при сборке

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/yuliya-sabirova/cpp-ads-course
  branch: main
  path_to_book: ""

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
